package sjtu.opennet.multicastfile.pb;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: multicastpb.proto

public final class Multicastpb {
  private Multicastpb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HONMultiPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HONMultiPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 文件的编号，用时间戳。
     * </pre>
     *
     * <code>uint64 fid = 1;</code>
     * @return The fid.
     */
    long getFid();

    /**
     * <pre>
     * 编码的组号
     * </pre>
     *
     * <code>uint32 gid = 2;</code>
     * @return The gid.
     */
    int getGid();

    /**
     * <pre>
     * 编码号，shard id
     * </pre>
     *
     * <code>uint32 sid = 3;</code>
     * @return The sid.
     */
    int getSid();

    /**
     * <code>bytes data = 5;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code HONMultiPacket}
   */
  public static final class HONMultiPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HONMultiPacket)
      HONMultiPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HONMultiPacket.newBuilder() to construct.
    private HONMultiPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HONMultiPacket() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HONMultiPacket();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HONMultiPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              fid_ = input.readUInt64();
              break;
            }
            case 16: {

              gid_ = input.readUInt32();
              break;
            }
            case 24: {

              sid_ = input.readUInt32();
              break;
            }
            case 42: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Multicastpb.internal_static_HONMultiPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Multicastpb.internal_static_HONMultiPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Multicastpb.HONMultiPacket.class, Multicastpb.HONMultiPacket.Builder.class);
    }

    public static final int FID_FIELD_NUMBER = 1;
    private long fid_;
    /**
     * <pre>
     * 文件的编号，用时间戳。
     * </pre>
     *
     * <code>uint64 fid = 1;</code>
     * @return The fid.
     */
    @java.lang.Override
    public long getFid() {
      return fid_;
    }

    public static final int GID_FIELD_NUMBER = 2;
    private int gid_;
    /**
     * <pre>
     * 编码的组号
     * </pre>
     *
     * <code>uint32 gid = 2;</code>
     * @return The gid.
     */
    @java.lang.Override
    public int getGid() {
      return gid_;
    }

    public static final int SID_FIELD_NUMBER = 3;
    private int sid_;
    /**
     * <pre>
     * 编码号，shard id
     * </pre>
     *
     * <code>uint32 sid = 3;</code>
     * @return The sid.
     */
    @java.lang.Override
    public int getSid() {
      return sid_;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 5;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (fid_ != 0L) {
        output.writeUInt64(1, fid_);
      }
      if (gid_ != 0) {
        output.writeUInt32(2, gid_);
      }
      if (sid_ != 0) {
        output.writeUInt32(3, sid_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(5, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (fid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, fid_);
      }
      if (gid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, gid_);
      }
      if (sid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, sid_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Multicastpb.HONMultiPacket)) {
        return super.equals(obj);
      }
      Multicastpb.HONMultiPacket other = (Multicastpb.HONMultiPacket) obj;

      if (getFid()
          != other.getFid()) return false;
      if (getGid()
          != other.getGid()) return false;
      if (getSid()
          != other.getSid()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFid());
      hash = (37 * hash) + GID_FIELD_NUMBER;
      hash = (53 * hash) + getGid();
      hash = (37 * hash) + SID_FIELD_NUMBER;
      hash = (53 * hash) + getSid();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Multicastpb.HONMultiPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Multicastpb.HONMultiPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Multicastpb.HONMultiPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Multicastpb.HONMultiPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Multicastpb.HONMultiPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Multicastpb.HONMultiPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Multicastpb.HONMultiPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Multicastpb.HONMultiPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Multicastpb.HONMultiPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Multicastpb.HONMultiPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Multicastpb.HONMultiPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Multicastpb.HONMultiPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Multicastpb.HONMultiPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HONMultiPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HONMultiPacket)
        Multicastpb.HONMultiPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Multicastpb.internal_static_HONMultiPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Multicastpb.internal_static_HONMultiPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Multicastpb.HONMultiPacket.class, Multicastpb.HONMultiPacket.Builder.class);
      }

      // Construct using Multicastpb.HONMultiPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fid_ = 0L;

        gid_ = 0;

        sid_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Multicastpb.internal_static_HONMultiPacket_descriptor;
      }

      @java.lang.Override
      public Multicastpb.HONMultiPacket getDefaultInstanceForType() {
        return Multicastpb.HONMultiPacket.getDefaultInstance();
      }

      @java.lang.Override
      public Multicastpb.HONMultiPacket build() {
        Multicastpb.HONMultiPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Multicastpb.HONMultiPacket buildPartial() {
        Multicastpb.HONMultiPacket result = new Multicastpb.HONMultiPacket(this);
        result.fid_ = fid_;
        result.gid_ = gid_;
        result.sid_ = sid_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Multicastpb.HONMultiPacket) {
          return mergeFrom((Multicastpb.HONMultiPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Multicastpb.HONMultiPacket other) {
        if (other == Multicastpb.HONMultiPacket.getDefaultInstance()) return this;
        if (other.getFid() != 0L) {
          setFid(other.getFid());
        }
        if (other.getGid() != 0) {
          setGid(other.getGid());
        }
        if (other.getSid() != 0) {
          setSid(other.getSid());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Multicastpb.HONMultiPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Multicastpb.HONMultiPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long fid_ ;
      /**
       * <pre>
       * 文件的编号，用时间戳。
       * </pre>
       *
       * <code>uint64 fid = 1;</code>
       * @return The fid.
       */
      @java.lang.Override
      public long getFid() {
        return fid_;
      }
      /**
       * <pre>
       * 文件的编号，用时间戳。
       * </pre>
       *
       * <code>uint64 fid = 1;</code>
       * @param value The fid to set.
       * @return This builder for chaining.
       */
      public Builder setFid(long value) {
        
        fid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文件的编号，用时间戳。
       * </pre>
       *
       * <code>uint64 fid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFid() {
        
        fid_ = 0L;
        onChanged();
        return this;
      }

      private int gid_ ;
      /**
       * <pre>
       * 编码的组号
       * </pre>
       *
       * <code>uint32 gid = 2;</code>
       * @return The gid.
       */
      @java.lang.Override
      public int getGid() {
        return gid_;
      }
      /**
       * <pre>
       * 编码的组号
       * </pre>
       *
       * <code>uint32 gid = 2;</code>
       * @param value The gid to set.
       * @return This builder for chaining.
       */
      public Builder setGid(int value) {
        
        gid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 编码的组号
       * </pre>
       *
       * <code>uint32 gid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGid() {
        
        gid_ = 0;
        onChanged();
        return this;
      }

      private int sid_ ;
      /**
       * <pre>
       * 编码号，shard id
       * </pre>
       *
       * <code>uint32 sid = 3;</code>
       * @return The sid.
       */
      @java.lang.Override
      public int getSid() {
        return sid_;
      }
      /**
       * <pre>
       * 编码号，shard id
       * </pre>
       *
       * <code>uint32 sid = 3;</code>
       * @param value The sid to set.
       * @return This builder for chaining.
       */
      public Builder setSid(int value) {
        
        sid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 编码号，shard id
       * </pre>
       *
       * <code>uint32 sid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSid() {
        
        sid_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 5;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 5;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HONMultiPacket)
    }

    // @@protoc_insertion_point(class_scope:HONMultiPacket)
    private static final Multicastpb.HONMultiPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Multicastpb.HONMultiPacket();
    }

    public static Multicastpb.HONMultiPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HONMultiPacket>
        PARSER = new com.google.protobuf.AbstractParser<HONMultiPacket>() {
      @java.lang.Override
      public HONMultiPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HONMultiPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HONMultiPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HONMultiPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Multicastpb.HONMultiPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FileMetaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FileMeta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string senderIP = 1;</code>
     * @return The senderIP.
     */
    java.lang.String getSenderIP();
    /**
     * <code>string senderIP = 1;</code>
     * @return The bytes for senderIP.
     */
    com.google.protobuf.ByteString
        getSenderIPBytes();

    /**
     * <code>uint64 fid = 2;</code>
     * @return The fid.
     */
    long getFid();

    /**
     * <code>uint32 fileSize = 3;</code>
     * @return The fileSize.
     */
    int getFileSize();

    /**
     * <code>string fileName = 4;</code>
     * @return The fileName.
     */
    java.lang.String getFileName();
    /**
     * <code>string fileName = 4;</code>
     * @return The bytes for fileName.
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>uint32 fileType = 5;</code>
     * @return The fileType.
     */
    int getFileType();

    /**
     * <code>string fileDescription = 6;</code>
     * @return The fileDescription.
     */
    java.lang.String getFileDescription();
    /**
     * <code>string fileDescription = 6;</code>
     * @return The bytes for fileDescription.
     */
    com.google.protobuf.ByteString
        getFileDescriptionBytes();

    /**
     * <code>string sender = 7;</code>
     * @return The sender.
     */
    java.lang.String getSender();
    /**
     * <code>string sender = 7;</code>
     * @return The bytes for sender.
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <code>uint32 gnum = 8;</code>
     * @return The gnum.
     */
    int getGnum();
  }
  /**
   * Protobuf type {@code FileMeta}
   */
  public static final class FileMeta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FileMeta)
      FileMetaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileMeta.newBuilder() to construct.
    private FileMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileMeta() {
      senderIP_ = "";
      fileName_ = "";
      fileDescription_ = "";
      sender_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileMeta();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileMeta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              senderIP_ = s;
              break;
            }
            case 16: {

              fid_ = input.readUInt64();
              break;
            }
            case 24: {

              fileSize_ = input.readUInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 40: {

              fileType_ = input.readUInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              fileDescription_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              sender_ = s;
              break;
            }
            case 64: {

              gnum_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Multicastpb.internal_static_FileMeta_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Multicastpb.internal_static_FileMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Multicastpb.FileMeta.class, Multicastpb.FileMeta.Builder.class);
    }

    public static final int SENDERIP_FIELD_NUMBER = 1;
    private volatile java.lang.Object senderIP_;
    /**
     * <code>string senderIP = 1;</code>
     * @return The senderIP.
     */
    @java.lang.Override
    public java.lang.String getSenderIP() {
      java.lang.Object ref = senderIP_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderIP_ = s;
        return s;
      }
    }
    /**
     * <code>string senderIP = 1;</code>
     * @return The bytes for senderIP.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderIPBytes() {
      java.lang.Object ref = senderIP_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FID_FIELD_NUMBER = 2;
    private long fid_;
    /**
     * <code>uint64 fid = 2;</code>
     * @return The fid.
     */
    @java.lang.Override
    public long getFid() {
      return fid_;
    }

    public static final int FILESIZE_FIELD_NUMBER = 3;
    private int fileSize_;
    /**
     * <code>uint32 fileSize = 3;</code>
     * @return The fileSize.
     */
    @java.lang.Override
    public int getFileSize() {
      return fileSize_;
    }

    public static final int FILENAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object fileName_;
    /**
     * <code>string fileName = 4;</code>
     * @return The fileName.
     */
    @java.lang.Override
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string fileName = 4;</code>
     * @return The bytes for fileName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILETYPE_FIELD_NUMBER = 5;
    private int fileType_;
    /**
     * <code>uint32 fileType = 5;</code>
     * @return The fileType.
     */
    @java.lang.Override
    public int getFileType() {
      return fileType_;
    }

    public static final int FILEDESCRIPTION_FIELD_NUMBER = 6;
    private volatile java.lang.Object fileDescription_;
    /**
     * <code>string fileDescription = 6;</code>
     * @return The fileDescription.
     */
    @java.lang.Override
    public java.lang.String getFileDescription() {
      java.lang.Object ref = fileDescription_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileDescription_ = s;
        return s;
      }
    }
    /**
     * <code>string fileDescription = 6;</code>
     * @return The bytes for fileDescription.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileDescriptionBytes() {
      java.lang.Object ref = fileDescription_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDER_FIELD_NUMBER = 7;
    private volatile java.lang.Object sender_;
    /**
     * <code>string sender = 7;</code>
     * @return The sender.
     */
    @java.lang.Override
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      }
    }
    /**
     * <code>string sender = 7;</code>
     * @return The bytes for sender.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GNUM_FIELD_NUMBER = 8;
    private int gnum_;
    /**
     * <code>uint32 gnum = 8;</code>
     * @return The gnum.
     */
    @java.lang.Override
    public int getGnum() {
      return gnum_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSenderIPBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, senderIP_);
      }
      if (fid_ != 0L) {
        output.writeUInt64(2, fid_);
      }
      if (fileSize_ != 0) {
        output.writeUInt32(3, fileSize_);
      }
      if (!getFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fileName_);
      }
      if (fileType_ != 0) {
        output.writeUInt32(5, fileType_);
      }
      if (!getFileDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, fileDescription_);
      }
      if (!getSenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, sender_);
      }
      if (gnum_ != 0) {
        output.writeUInt32(8, gnum_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSenderIPBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, senderIP_);
      }
      if (fid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, fid_);
      }
      if (fileSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, fileSize_);
      }
      if (!getFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fileName_);
      }
      if (fileType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, fileType_);
      }
      if (!getFileDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, fileDescription_);
      }
      if (!getSenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, sender_);
      }
      if (gnum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, gnum_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Multicastpb.FileMeta)) {
        return super.equals(obj);
      }
      Multicastpb.FileMeta other = (Multicastpb.FileMeta) obj;

      if (!getSenderIP()
          .equals(other.getSenderIP())) return false;
      if (getFid()
          != other.getFid()) return false;
      if (getFileSize()
          != other.getFileSize()) return false;
      if (!getFileName()
          .equals(other.getFileName())) return false;
      if (getFileType()
          != other.getFileType()) return false;
      if (!getFileDescription()
          .equals(other.getFileDescription())) return false;
      if (!getSender()
          .equals(other.getSender())) return false;
      if (getGnum()
          != other.getGnum()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDERIP_FIELD_NUMBER;
      hash = (53 * hash) + getSenderIP().hashCode();
      hash = (37 * hash) + FID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFid());
      hash = (37 * hash) + FILESIZE_FIELD_NUMBER;
      hash = (53 * hash) + getFileSize();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + FILETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getFileType();
      hash = (37 * hash) + FILEDESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getFileDescription().hashCode();
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender().hashCode();
      hash = (37 * hash) + GNUM_FIELD_NUMBER;
      hash = (53 * hash) + getGnum();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Multicastpb.FileMeta parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Multicastpb.FileMeta parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Multicastpb.FileMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Multicastpb.FileMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Multicastpb.FileMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Multicastpb.FileMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Multicastpb.FileMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Multicastpb.FileMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Multicastpb.FileMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Multicastpb.FileMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Multicastpb.FileMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Multicastpb.FileMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Multicastpb.FileMeta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FileMeta)
        Multicastpb.FileMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Multicastpb.internal_static_FileMeta_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Multicastpb.internal_static_FileMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Multicastpb.FileMeta.class, Multicastpb.FileMeta.Builder.class);
      }

      // Construct using Multicastpb.FileMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        senderIP_ = "";

        fid_ = 0L;

        fileSize_ = 0;

        fileName_ = "";

        fileType_ = 0;

        fileDescription_ = "";

        sender_ = "";

        gnum_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Multicastpb.internal_static_FileMeta_descriptor;
      }

      @java.lang.Override
      public Multicastpb.FileMeta getDefaultInstanceForType() {
        return Multicastpb.FileMeta.getDefaultInstance();
      }

      @java.lang.Override
      public Multicastpb.FileMeta build() {
        Multicastpb.FileMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Multicastpb.FileMeta buildPartial() {
        Multicastpb.FileMeta result = new Multicastpb.FileMeta(this);
        result.senderIP_ = senderIP_;
        result.fid_ = fid_;
        result.fileSize_ = fileSize_;
        result.fileName_ = fileName_;
        result.fileType_ = fileType_;
        result.fileDescription_ = fileDescription_;
        result.sender_ = sender_;
        result.gnum_ = gnum_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Multicastpb.FileMeta) {
          return mergeFrom((Multicastpb.FileMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Multicastpb.FileMeta other) {
        if (other == Multicastpb.FileMeta.getDefaultInstance()) return this;
        if (!other.getSenderIP().isEmpty()) {
          senderIP_ = other.senderIP_;
          onChanged();
        }
        if (other.getFid() != 0L) {
          setFid(other.getFid());
        }
        if (other.getFileSize() != 0) {
          setFileSize(other.getFileSize());
        }
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.getFileType() != 0) {
          setFileType(other.getFileType());
        }
        if (!other.getFileDescription().isEmpty()) {
          fileDescription_ = other.fileDescription_;
          onChanged();
        }
        if (!other.getSender().isEmpty()) {
          sender_ = other.sender_;
          onChanged();
        }
        if (other.getGnum() != 0) {
          setGnum(other.getGnum());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Multicastpb.FileMeta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Multicastpb.FileMeta) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object senderIP_ = "";
      /**
       * <code>string senderIP = 1;</code>
       * @return The senderIP.
       */
      public java.lang.String getSenderIP() {
        java.lang.Object ref = senderIP_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderIP_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senderIP = 1;</code>
       * @return The bytes for senderIP.
       */
      public com.google.protobuf.ByteString
          getSenderIPBytes() {
        java.lang.Object ref = senderIP_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderIP_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senderIP = 1;</code>
       * @param value The senderIP to set.
       * @return This builder for chaining.
       */
      public Builder setSenderIP(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderIP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string senderIP = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderIP() {
        
        senderIP_ = getDefaultInstance().getSenderIP();
        onChanged();
        return this;
      }
      /**
       * <code>string senderIP = 1;</code>
       * @param value The bytes for senderIP to set.
       * @return This builder for chaining.
       */
      public Builder setSenderIPBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderIP_ = value;
        onChanged();
        return this;
      }

      private long fid_ ;
      /**
       * <code>uint64 fid = 2;</code>
       * @return The fid.
       */
      @java.lang.Override
      public long getFid() {
        return fid_;
      }
      /**
       * <code>uint64 fid = 2;</code>
       * @param value The fid to set.
       * @return This builder for chaining.
       */
      public Builder setFid(long value) {
        
        fid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 fid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFid() {
        
        fid_ = 0L;
        onChanged();
        return this;
      }

      private int fileSize_ ;
      /**
       * <code>uint32 fileSize = 3;</code>
       * @return The fileSize.
       */
      @java.lang.Override
      public int getFileSize() {
        return fileSize_;
      }
      /**
       * <code>uint32 fileSize = 3;</code>
       * @param value The fileSize to set.
       * @return This builder for chaining.
       */
      public Builder setFileSize(int value) {
        
        fileSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 fileSize = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileSize() {
        
        fileSize_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>string fileName = 4;</code>
       * @return The fileName.
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileName = 4;</code>
       * @return The bytes for fileName.
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileName = 4;</code>
       * @param value The fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 4;</code>
       * @param value The bytes for fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private int fileType_ ;
      /**
       * <code>uint32 fileType = 5;</code>
       * @return The fileType.
       */
      @java.lang.Override
      public int getFileType() {
        return fileType_;
      }
      /**
       * <code>uint32 fileType = 5;</code>
       * @param value The fileType to set.
       * @return This builder for chaining.
       */
      public Builder setFileType(int value) {
        
        fileType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 fileType = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileType() {
        
        fileType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fileDescription_ = "";
      /**
       * <code>string fileDescription = 6;</code>
       * @return The fileDescription.
       */
      public java.lang.String getFileDescription() {
        java.lang.Object ref = fileDescription_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileDescription_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileDescription = 6;</code>
       * @return The bytes for fileDescription.
       */
      public com.google.protobuf.ByteString
          getFileDescriptionBytes() {
        java.lang.Object ref = fileDescription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileDescription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileDescription = 6;</code>
       * @param value The fileDescription to set.
       * @return This builder for chaining.
       */
      public Builder setFileDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileDescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileDescription = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileDescription() {
        
        fileDescription_ = getDefaultInstance().getFileDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string fileDescription = 6;</code>
       * @param value The bytes for fileDescription to set.
       * @return This builder for chaining.
       */
      public Builder setFileDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileDescription_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sender_ = "";
      /**
       * <code>string sender = 7;</code>
       * @return The sender.
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sender = 7;</code>
       * @return The bytes for sender.
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sender = 7;</code>
       * @param value The sender to set.
       * @return This builder for chaining.
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sender = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSender() {
        
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <code>string sender = 7;</code>
       * @param value The bytes for sender to set.
       * @return This builder for chaining.
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sender_ = value;
        onChanged();
        return this;
      }

      private int gnum_ ;
      /**
       * <code>uint32 gnum = 8;</code>
       * @return The gnum.
       */
      @java.lang.Override
      public int getGnum() {
        return gnum_;
      }
      /**
       * <code>uint32 gnum = 8;</code>
       * @param value The gnum to set.
       * @return This builder for chaining.
       */
      public Builder setGnum(int value) {
        
        gnum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 gnum = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearGnum() {
        
        gnum_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FileMeta)
    }

    // @@protoc_insertion_point(class_scope:FileMeta)
    private static final Multicastpb.FileMeta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Multicastpb.FileMeta();
    }

    public static Multicastpb.FileMeta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileMeta>
        PARSER = new com.google.protobuf.AbstractParser<FileMeta>() {
      @java.lang.Override
      public FileMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileMeta(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileMeta> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileMeta> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Multicastpb.FileMeta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FileGroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FileGroup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.FileMeta meta = 1;</code>
     * @return Whether the meta field is set.
     */
    boolean hasMeta();
    /**
     * <code>.FileMeta meta = 1;</code>
     * @return The meta.
     */
    Multicastpb.FileMeta getMeta();
    /**
     * <code>.FileMeta meta = 1;</code>
     */
    Multicastpb.FileMetaOrBuilder getMetaOrBuilder();

    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code FileGroup}
   */
  public static final class FileGroup extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FileGroup)
      FileGroupOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileGroup.newBuilder() to construct.
    private FileGroup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileGroup() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileGroup();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Multicastpb.FileMeta.Builder subBuilder = null;
              if (meta_ != null) {
                subBuilder = meta_.toBuilder();
              }
              meta_ = input.readMessage(Multicastpb.FileMeta.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(meta_);
                meta_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Multicastpb.internal_static_FileGroup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Multicastpb.internal_static_FileGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Multicastpb.FileGroup.class, Multicastpb.FileGroup.Builder.class);
    }

    public static final int META_FIELD_NUMBER = 1;
    private Multicastpb.FileMeta meta_;
    /**
     * <code>.FileMeta meta = 1;</code>
     * @return Whether the meta field is set.
     */
    @java.lang.Override
    public boolean hasMeta() {
      return meta_ != null;
    }
    /**
     * <code>.FileMeta meta = 1;</code>
     * @return The meta.
     */
    @java.lang.Override
    public Multicastpb.FileMeta getMeta() {
      return meta_ == null ? Multicastpb.FileMeta.getDefaultInstance() : meta_;
    }
    /**
     * <code>.FileMeta meta = 1;</code>
     */
    @java.lang.Override
    public Multicastpb.FileMetaOrBuilder getMetaOrBuilder() {
      return getMeta();
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (meta_ != null) {
        output.writeMessage(1, getMeta());
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (meta_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMeta());
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Multicastpb.FileGroup)) {
        return super.equals(obj);
      }
      Multicastpb.FileGroup other = (Multicastpb.FileGroup) obj;

      if (hasMeta() != other.hasMeta()) return false;
      if (hasMeta()) {
        if (!getMeta()
            .equals(other.getMeta())) return false;
      }
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMeta()) {
        hash = (37 * hash) + META_FIELD_NUMBER;
        hash = (53 * hash) + getMeta().hashCode();
      }
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Multicastpb.FileGroup parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Multicastpb.FileGroup parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Multicastpb.FileGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Multicastpb.FileGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Multicastpb.FileGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Multicastpb.FileGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Multicastpb.FileGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Multicastpb.FileGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Multicastpb.FileGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Multicastpb.FileGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Multicastpb.FileGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Multicastpb.FileGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Multicastpb.FileGroup prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FileGroup)
        Multicastpb.FileGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Multicastpb.internal_static_FileGroup_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Multicastpb.internal_static_FileGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Multicastpb.FileGroup.class, Multicastpb.FileGroup.Builder.class);
      }

      // Construct using Multicastpb.FileGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (metaBuilder_ == null) {
          meta_ = null;
        } else {
          meta_ = null;
          metaBuilder_ = null;
        }
        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Multicastpb.internal_static_FileGroup_descriptor;
      }

      @java.lang.Override
      public Multicastpb.FileGroup getDefaultInstanceForType() {
        return Multicastpb.FileGroup.getDefaultInstance();
      }

      @java.lang.Override
      public Multicastpb.FileGroup build() {
        Multicastpb.FileGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Multicastpb.FileGroup buildPartial() {
        Multicastpb.FileGroup result = new Multicastpb.FileGroup(this);
        if (metaBuilder_ == null) {
          result.meta_ = meta_;
        } else {
          result.meta_ = metaBuilder_.build();
        }
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Multicastpb.FileGroup) {
          return mergeFrom((Multicastpb.FileGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Multicastpb.FileGroup other) {
        if (other == Multicastpb.FileGroup.getDefaultInstance()) return this;
        if (other.hasMeta()) {
          mergeMeta(other.getMeta());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Multicastpb.FileGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Multicastpb.FileGroup) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Multicastpb.FileMeta meta_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Multicastpb.FileMeta, Multicastpb.FileMeta.Builder, Multicastpb.FileMetaOrBuilder> metaBuilder_;
      /**
       * <code>.FileMeta meta = 1;</code>
       * @return Whether the meta field is set.
       */
      public boolean hasMeta() {
        return metaBuilder_ != null || meta_ != null;
      }
      /**
       * <code>.FileMeta meta = 1;</code>
       * @return The meta.
       */
      public Multicastpb.FileMeta getMeta() {
        if (metaBuilder_ == null) {
          return meta_ == null ? Multicastpb.FileMeta.getDefaultInstance() : meta_;
        } else {
          return metaBuilder_.getMessage();
        }
      }
      /**
       * <code>.FileMeta meta = 1;</code>
       */
      public Builder setMeta(Multicastpb.FileMeta value) {
        if (metaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          meta_ = value;
          onChanged();
        } else {
          metaBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.FileMeta meta = 1;</code>
       */
      public Builder setMeta(
          Multicastpb.FileMeta.Builder builderForValue) {
        if (metaBuilder_ == null) {
          meta_ = builderForValue.build();
          onChanged();
        } else {
          metaBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.FileMeta meta = 1;</code>
       */
      public Builder mergeMeta(Multicastpb.FileMeta value) {
        if (metaBuilder_ == null) {
          if (meta_ != null) {
            meta_ =
              Multicastpb.FileMeta.newBuilder(meta_).mergeFrom(value).buildPartial();
          } else {
            meta_ = value;
          }
          onChanged();
        } else {
          metaBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.FileMeta meta = 1;</code>
       */
      public Builder clearMeta() {
        if (metaBuilder_ == null) {
          meta_ = null;
          onChanged();
        } else {
          meta_ = null;
          metaBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.FileMeta meta = 1;</code>
       */
      public Multicastpb.FileMeta.Builder getMetaBuilder() {
        
        onChanged();
        return getMetaFieldBuilder().getBuilder();
      }
      /**
       * <code>.FileMeta meta = 1;</code>
       */
      public Multicastpb.FileMetaOrBuilder getMetaOrBuilder() {
        if (metaBuilder_ != null) {
          return metaBuilder_.getMessageOrBuilder();
        } else {
          return meta_ == null ?
              Multicastpb.FileMeta.getDefaultInstance() : meta_;
        }
      }
      /**
       * <code>.FileMeta meta = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Multicastpb.FileMeta, Multicastpb.FileMeta.Builder, Multicastpb.FileMetaOrBuilder> 
          getMetaFieldBuilder() {
        if (metaBuilder_ == null) {
          metaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Multicastpb.FileMeta, Multicastpb.FileMeta.Builder, Multicastpb.FileMetaOrBuilder>(
                  getMeta(),
                  getParentForChildren(),
                  isClean());
          meta_ = null;
        }
        return metaBuilder_;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 2;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FileGroup)
    }

    // @@protoc_insertion_point(class_scope:FileGroup)
    private static final Multicastpb.FileGroup DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Multicastpb.FileGroup();
    }

    public static Multicastpb.FileGroup getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileGroup>
        PARSER = new com.google.protobuf.AbstractParser<FileGroup>() {
      @java.lang.Override
      public FileGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileGroup(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileGroup> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileGroup> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Multicastpb.FileGroup getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HONMultiPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HONMultiPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileMeta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileMeta_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileGroup_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021multicastpb.proto\032\037google/protobuf/tim" +
      "estamp.proto\032\031google/protobuf/any.proto\"" +
      "E\n\016HONMultiPacket\022\013\n\003fid\030\001 \001(\004\022\013\n\003gid\030\002 " +
      "\001(\r\022\013\n\003sid\030\003 \001(\r\022\014\n\004data\030\005 \001(\014\"\226\001\n\010FileM" +
      "eta\022\020\n\010senderIP\030\001 \001(\t\022\013\n\003fid\030\002 \001(\004\022\020\n\010fi" +
      "leSize\030\003 \001(\r\022\020\n\010fileName\030\004 \001(\t\022\020\n\010fileTy" +
      "pe\030\005 \001(\r\022\027\n\017fileDescription\030\006 \001(\t\022\016\n\006sen" +
      "der\030\007 \001(\t\022\014\n\004gnum\030\010 \001(\r\"2\n\tFileGroup\022\027\n\004" +
      "meta\030\001 \001(\0132\t.FileMeta\022\014\n\004data\030\002 \001(\014b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_HONMultiPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HONMultiPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HONMultiPacket_descriptor,
        new java.lang.String[] { "Fid", "Gid", "Sid", "Data", });
    internal_static_FileMeta_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FileMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileMeta_descriptor,
        new java.lang.String[] { "SenderIP", "Fid", "FileSize", "FileName", "FileType", "FileDescription", "Sender", "Gnum", });
    internal_static_FileGroup_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FileGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileGroup_descriptor,
        new java.lang.String[] { "Meta", "Data", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
